# Generated by Django 5.0.3 on 2024-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_m',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=20)),
                ('owner_id', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, height_field=12, null=True, upload_to='', width_field=12)),
            ],
        ),
    ]
